version: '3'
services:
  backend:
    image: wpcfan/lowcode:latest
    container_name: backend
    environment:
      - REDIS_URL=redis://redis:6379
      - MYSQL_URL=jdbc:mysql://mysql:3306/low_code?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ../frontend/admin/build/web:/usr/share/nginx/html
      - ../frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
  redis:
    extends:
      service: redis
      file: docker-compose.redis.yml
  mysql:
    extends:
      service: mysql
      file: docker-compose.mysql.yml