CREATE TABLE mooc_categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_mooc_categories PRIMARY KEY (id)
);

CREATE TABLE mooc_products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku            VARCHAR(255),
    name           VARCHAR(255),
    description    VARCHAR(255),
    price          DECIMAL,
    original_price DECIMAL,
    CONSTRAINT pk_mooc_products PRIMARY KEY (id)
);

CREATE TABLE mooc_products_categories
(
    categories_id BIGINT NOT NULL,
    product_id    BIGINT NOT NULL,
    CONSTRAINT pk_mooc_products_categories PRIMARY KEY (categories_id, product_id)
);

ALTER TABLE mooc_products_categories
    ADD CONSTRAINT fk_mooc_products_categories_on_category FOREIGN KEY (categories_id) REFERENCES mooc_categories (id);

ALTER TABLE mooc_products_categories
    ADD CONSTRAINT fk_mooc_products_categories_on_product FOREIGN KEY (product_id) REFERENCES mooc_products (id);